DROP TABLE IF EXISTS `shop_info`;
CREATE TABLE `shop_info` (
	`id` INT(200) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NULL DEFAULT NULL COMMENT '名称',
	`code` VARCHAR(20) NULL DEFAULT NULL COMMENT '代码',
	`managers` VARCHAR(50) NULL DEFAULT NULL COMMENT '负责人',
	`phone` VARCHAR(20) NULL DEFAULT NULL COMMENT '电话',
	`mail` VARCHAR(100) NULL DEFAULT NULL COMMENT '邮箱',
	`address` VARCHAR(1024) NULL DEFAULT NULL COMMENT '地址',
	`status` int(2) NULL DEFAULT NULL COMMENT '状态',
	`create_time` TIMESTAMP null DEFAULT CURRENT_TIMESTAMP  COMMENT '创建时间',
	`modify_time` TIMESTAMP null COMMENT '创建时间',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;